/* Database schema */

/* Create animals table */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(60) NOT NULL, 
    date_of_birth DATE NOT NULL, 
    escape_attempts INT NOT NULL, 
    neutered BOOLEAN, 
    weight_kg DECIMAL NOT NULL
);

/* Update animals table */

ALTER TABLE animals
ADD COLUMN species VARCHAR(60)