/* Database schema */

/* Create animals table */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(60) NOT NULL, 
    date_of_birth DATE NOT NULL, 
    escape_attempts INT NOT NULL, 
    neutered BOOLEAN, 
    weight_kg DECIMAL NOT NULL
);

/* Update animals table */

ALTER TABLE animals
ADD COLUMN species VARCHAR(60)


/*  Query multiple tables  */

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    full_name VARCHAR(60),
    age INT
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(60)
);

ALTER TABLE animals                                                                    
ALTER COLUMN id SET NOT NULL;

ALTER TABLE animals
ALTER id
ADD GENERATED ALWAYS  AS IDENTITY,
ADD PRIMARY KEY(id);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners(id);


CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    date_of_graduation DATE
);

CREATE TABLE specializations (
      species_id INT NOT NULL  REFERENCES species(id),
      vet_id INT NOT NULL   REFERENCES vets(id),
      PRIMARY KEY( species_id,vet_id) UNIQUE
);


CREATE TABLE visits (
      animal_id INT NOT NULL   REFERENCES animals(id),
      vet_id INT NOT NULL  REFERENCES vets(id),
      visit_date DATE NOT NULL   
);